In [ ]:
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install scipy

In [ ]:
import numpy as np
x = np.array([1,2,3,5,5])

In [ ]:
#mean using numpy
print("data", x)
print("mean : ", np.mean(x))

#finding median of x
print("data", x)
print("median : ", np.median(x))

#finding mode using numpy
print("data", x)
vals, counts = np.unique(x, return_counts = True)
index = np.argmax(counts)
print("mode : ", vals[index])

#finding mode using scipy
from scipy import stats
print("mode : ", stats.mode(x))

#calculating the range
print("data", x)
print("range : ", x.max()-x.min())

data [1 2 3 5 5]
mean :  3.2
data [1 2 3 5 5]
median :  3.0
data [1 2 3 5 5]
mode :  5
mode :  ModeResult(mode=array([5]), count=array([2]))
data [1 2 3 5 5]
range :  4


In [ ]:
from numpy.lib.function_base import percentile
#defining data
data1 = np.array([1,3,4,5,5,6,7,11])
print("data", data1)

#first quartile (Q1)
Q1 = np.quantile(data1, .25, interpolation = 'midpoint')
print("\nQuartile 1 : ", Q1)

#Q2
Q2 = np.quantile(data1, .50, interpolation = 'midpoint')
print("\nQuartile 2 : ", Q2)

#Q3
Q3 = np.quantile(data1, .75, interpolation = 'midpoint')
print("\nQuartile 3 : ", Q3)

#interquartile range (IQR)
IQR = Q3-Q1
print("\nInterquartile Range", IQR)

print("data", data1)
percentile_20 = np.percentile(data1, 20)
print("20th percentile : ", round(percentile_20, 2))

data [ 1  3  4  5  5  6  7 11]

Quartile 1 :  3.5

Quartile 2 :  5.0

Quartile 3 :  6.5

Interquartile Range 3.0
data [ 1  3  4  5  5  6  7 11]
20th percentile :  3.4


In [ ]:
print("data", data1)
'''
    "delta degrees of freedom": the divisior used in the calculation is
    ''n - ddof'', where ''n'' represents the number of elements. by
    default 'ddof' is zero.
'''
print("varaince : ", np.var(data1, ddof = 1))
print("standard deviation : ", np.std(data1, ddof = 1))

data [ 1  3  4  5  5  6  7 11]
varaince :  8.785714285714286
standard deviation :  2.9640705601780613


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = np.array([9,8,7,6,5,4,3,2,1])
print(y)

print("\nCovariance", np.cov(x,y)[0,1])

#return a correlation coefficient matrix
print(np.corrcoef(x,y))

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]

Covariance -7.5
[[ 1. -1.]
 [-1.  1.]]
